FROM microsoft/dotnet:2.1-sdk AS build-env

COPY /src /build/src
WORKDIR /build/src
RUN dotnet restore
RUN dotnet publish --configuration Release --output /build/out

FROM microsoft/dotnet:2.1-runtime-stretch-slim-arm32v7
WORKDIR /docker
COPY --from=build-env /build/out ./

RUN useradd -ms /bin/bash moduleuser
USER moduleuser

ENTRYPOINT ["dotnet", "OpcPublisher.dll"]
