FROM microsoft/dotnet:2.0-sdk-jessie

RUN apt-get update && apt-get install -y unzip \
	&& curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l ~/vsdbg
ENV PATH="${PATH}:/root/vsdbg/vsdbg"

COPY /src /build/src

WORKDIR /build/src
RUN dotnet restore
RUN dotnet publish --configuration Debug --output /build/out

WORKDIR /docker
ENTRYPOINT ["dotnet", "/build/out/OpcPublisher.dll"]
